version: 2.1

jobs:
  build-and-deploy:
    docker:
      - image: node:20.3.0
    steps:
      - checkout

      - run:
          name: Enable Corepack and activate pnpm
          command: |
            corepack enable
            corepack prepare pnpm@8.6.3 --activate

      - run:
          name: Install dependencies
          command: pnpm install

      - run:
          name: Run lint check
          command: pnpm lint

      - run:
          name: Run type check
          command: pnpm check

      - run:
          name: Run unit tests
          command: pnpm test:unit

      - run:
          name: Run end-to-end tests
          command: pnpm test:e2e

      - run:
          name: Build project
          command: pnpm run build

      - run:
          name: Deploy to GitHub Pages
          command: pnpm run deploy

workflows:
  build-and-test:
    jobs:
      - build-and-deploy